Improve ConnectionError message
When a request doesn't match the responses mock the error message isn't
very helpful. It tells you the request that was made which doesn't match
any mock, but it doesn't show you what responses have been registered.

This PR shows the request that has been made together with registered
responses. It makes it easier to spot why a test is failing because you
can compare the request with the mocks side by side.

Prior output:
```
requests.exceptions.ConnectionError: Connection refused by Responses: GET https://graph.facebook.com/v5.0/search?access_token=testac&type=adinterestvalid&interest_fbid_list=%5B%22123%22%5D doesn't match Responses Mock
```

New output:
```
requests.exceptions.ConnectionError: Connection refused by Responses - the call doesn't match any registered mock.

Request:
-GET https://graph.facebook.com/v5.0/search?access_token=testac&type=adinterestvalid&interest_fbid_list=%5B%22123%22%5D

Available matches:
- GET https://graph.facebook.com/v5.0/me/adaccounts?access_token=testac&summary=true
- GET https://graph.facebook.com/v5.0//search?access_token=testac&type=adinterestvalid&interest_fbid_list=%5B%22123%22%5D
```