chore: UserWarning if body provided for unsupported status
After the change to urllib3 v2, certain status codes are not expected
to have any content returned in the response. If they do have content
then requests (via urllib3) will cause an error like:
  requests.exceptions.ChunkedEncodingError: ('Connection broken: IncompleteRead(18 bytes read, -18 more expected)', IncompleteRead(18 bytes read, -18 more expected))

This can be confusing to users using responses who had set a body in
previous versions of urllib3 without any issues. Emit a `UserWarning`
to help users remedy the issue.